const xoConfigRules = require('eslint-config-xo').rules;

module.exports = {
	parser: require.resolve('vue-eslint-parser'),
	parserOptions: {
		ecmaVersion: 2018,
		sourceType: 'module',
		ecmaFeatures: {
			jsx: true
		}
	},
	env: {
		browser: true,
		es6: true
	},
	plugins: ['vue'],
	rules: {
		'vue/attribute-hyphenation': ['error', 'always'],
		'vue/attributes-order': 'warn',
		'vue/block-spacing': 'warn',
		'vue/brace-style': xoConfigRules['brace-style'],
		'vue/camelcase': xoConfigRules['camelcase'],
		'vue/comma-dangle': xoConfigRules['comma-dangle'],
		'vue/comment-directive': 'error',
		'vue/component-name-in-template-casing': ['error', "PascalCase", {"registeredComponentsOnly": false}],
		'vue/dot-location': 'error',
		'vue/eqeqeq': 'error',
		'vue/html-closing-bracket-newline': 'error',
		'vue/html-closing-bracket-spacing': 'error',
		'vue/html-end-tags': 'error',
		'vue/html-indent': 'error',
		'vue/html-quotes': 'error',
		'vue/html-self-closing': 'error',
		'vue/jsx-uses-vars': 'error',
		'vue/key-spacing': 'error',
		'vue/keyword-spacing': 'error',
		'vue/match-component-file-name': 'error',
		'vue/max-attributes-per-line': 'error',
		'vue/multiline-html-element-content-newline': 'error',
		'vue/mustache-interpolation-spacing': 'error',
		'vue/name-property-casing': 'error',
		'vue/no-async-in-computed-properties': 'error',
		'vue/no-boolean-default': 'error',
		'vue/no-confusing-v-for-v-if': 'error',
		'vue/no-deprecated-scope-attribute': 'error',
		'vue/no-dupe-keys': 'error',
		'vue/no-duplicate-attributes': 'error',
		'vue/no-empty-pattern': 'error',
		'vue/no-multi-spaces': 'error',
		'vue/no-parsing-error': 'error',
		'vue/no-reserved-keys': 'error',
		'vue/no-restricted-syntax': 'error',
		'vue/no-shared-component-data': 'error',
		'vue/no-side-effects-in-computed-properties': 'error',
		'vue/no-spaces-around-equal-signs-in-attribute': 'error',
		'vue/no-template-key': 'error',
		'vue/no-template-shadow': 'error',
		'vue/no-textarea-mustache': 'error',
		'vue/no-unused-components': 'error',
		'vue/no-unused-vars': 'error',
		'vue/no-use-v-if-with-v-for': 'error',
		'vue/no-v-html': 'error',
		'vue/object-curly-spacing': 'error',
		'vue/order-in-components': 'error',
		'vue/prop-name-casing': 'error',
		'vue/require-component-is': 'error',
		'vue/require-default-prop': 'error',
		'vue/require-direct-export': 'error',
		'vue/require-prop-type-constructor': 'error',
		'vue/require-prop-types': 'error',
		'vue/require-render-return': 'error',
		'vue/require-v-for-key': 'error',
		'vue/require-valid-default-prop': 'error',
		'vue/return-in-computed-property': 'error',
		'vue/script-indent': 'error',
		'vue/singleline-html-element-content-newline': 'error',
		'vue/space-infix-ops': 'error',
		'vue/space-unary-ops': 'error',
		'vue/this-in-template': 'error',
		'vue/use-v-on-exact': 'error',
		'vue/v-bind-style': 'error',
		'vue/v-on-function-call': 'error',
		'vue/v-on-style': 'error',
		'vue/valid-template-root': 'error',
		'vue/valid-v-bind': 'error',
		'vue/valid-v-cloak': 'error',
		'vue/valid-v-else-if': 'error',
		'vue/valid-v-else': 'error',
		'vue/valid-v-for': 'error',
		'vue/valid-v-html': 'error',
		'vue/valid-v-if': 'error',
		'vue/valid-v-model': 'error',
		'vue/valid-v-on': 'error',
		'vue/valid-v-once': 'error',
		'vue/valid-v-pre': 'error',
		'vue/valid-v-show': 'error',
		'valid-v-text': 'error'
	}
};
